project:
  type: book
  output-dir: _book
  #output-file: "Data-documentation-R-Quarto"

book:
  title: "Data documentation with R and Quarto"
  author:
    - "Noel Wytopil (presenter)"
    - "Sonja Gelzenleuchter (presenter & creator)"
    - "Sven Rieger (creater)"
  date: "13. April 2023"
  page-navigation: true
  open-graph: true
  #page-footer: "This is a Quarto book."
  back-to-top-navigation: true
  search: true
  reader-mode: true
  repo-url: https://github.com/RiegerSven/data-doc-workshop-2023
  repo-actions: [edit, issue]
  sidebar:
    style: docked
    background: light
  chapters:
    - part: "Preface and Introduction"
      chapters:
        - index.qmd
        - intro.qmd
        - gen-info.qmd
    - part: "Software"
      chapters:
        - intro-r-rstudio.qmd
        - intro-quarto.qmd
    - part: "Working with data"
      chapters:
        - imp-data.qmd
        - data-cleaning.qmd
        - data-proc.qmd
        - item-analy-descr.qmd
    - references.qmd

bibliography: ["r-refs.bib", "references.bib"]
csl: apa7.csl

format:
  html:
    theme: cosmo
    toc-depth: 4
    number-sections: true
    linestretch: 1.7
    code-copy: true
    code-link: true
    code-tools: true
    code-line-numbers: false
    code-fold: show
    code-summary: "Show/hide code"
    link-external-newwindow: true
    grid:
      sidebar-width: 275px
      margin-width: 275px
      body-width: 600px

